### PR TITLE
Fix files not being found

### PR DESCRIPTION
**Pull request by MarvinKlein1508**
Uploaded files are not visible within the filemanager. This commit fixes this issue.

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Not sure where that information originates from. Get it approved on the MB, first and we'll see.

**Comment by MarvinKlein1508** [comment]
@TheCartpenter the MB is also different. https://github.com/opencart/opencart/blob/ed199ee957429ae0dda001a0820d31e8a2c515ea/upload/admin/controller/common/filemanager.php#L48

You will see what this does when you do the following:
1. Open any product
2. Visit images tab
3. Upload an image
4. notice the image is on imaga/catalog but won't be displayed on filemanager.

**Comment by TheCartpenter** [comment]
The MB does NOT include the / in front of the star. It is NOT identical.

**Comment by MarvinKlein1508** [comment]
@TheCartpenter the fact is that both mine and the MB works. I can put the slash in front if you want. Should I keep your `ico` addition or should I revert the functionality to the original MB?

**Comment by MarvinKlein1508** [comment]
Here is a video of the issue with current installation of your main branch.
https://youtu.be/zn7L_TMiGWM

**Comment by TheCartpenter** [comment]
Your code is in regard to add a slash in front of the star. Therefore, since you claim that only with the slash it works on this branch and, since that line is identical with the one on the MB, get it approved on the MB with the slash and see if that will fit in. As for the installation issue, please separate pull requests based on their specific issues.

**Comment by TheCartpenter** [comment]
So to add, with your video, you are testing this on a virtual server whereas this line of code is also identical with the MB.

**Comment by MarvinKlein1508** [comment]
@TheCartpenter I don't think you understand what I mean.

It doesn't matter if the slash is in the front or in the back. You can also put in the same code as in the Maintenance branch. The difference here is within your curly braces for your file extensions.

Your code:
```php
$files = glob($directory . $filter_name . '*{/,.ico,.jpg,.jpeg,.png,.gif,.webp,.JPG,.JPEG,.PNG,.GIF}', GLOB_BRACE);
```

Maintenance:
```php
$files = glob($directory . '/' . $filter_name . '*.{jpg,jpeg,png,gif,webp,JPG,JPEG,PNG,GIF,WEBP}', GLOB_BRACE);
```

My version:
```php
$files = glob($directory . $filter_name . '/*.{ico,jpg,jpeg,png,gif,webp,JPG,JPEG,PNG,GIF}', GLOB_BRACE);
```

As you can see the / in the maintenance branch is not part of the extension list and the extensions are without a leading `.` 

The reason I've put the slash before the `*` is because it's put in the curly braces in your version. Fact is that both mine and the Maintenance version works fine and the version from your main branch does not.

I'm not testing it on a virtual server. We have your main branch running on a real server where this issue also persists. You can check for yourself. Just install your main branch on any server you want and upload an image within the administration.

So the only question remains is should I revert it to the original Maintenace branch or should I keep like this with your changed file extension list?

**Pull request closed without merging**
