### PR TITLE
Changed Admin Affiliate code structure

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
The model and the TWIG files for the affiliate URL might be needed here as well.

**Comment by condor2** [comment]
What model and twig?

affiliate model from marketing is in this pull
same for affiliate_list, affiliate_form, affiliate_report

**Comment by TheCartpenter** [comment]
Correct, I see it now. However, you're missing the backquotes on your SQL tables and fields in the marketing model you're proposing. These needs to be added.

**Comment by TheCartpenter** [comment]
Furthermore, the 1009.php upgrade file and install/opencart.sql file will also need to impose these changes.

**Comment by condor2** [comment]
On upgrade oc_affiliate_report will be created from opencart.sql

**Comment by TheCartpenter** [comment]
Since the oc_affiliate_report table doesn't exist from either file, OC 3 releases as opposed to the OC 4 db_schema, queries must be handled from the upgrade files as well which, in this case, 1009.php file needs to have for store owners that will upgrade their stores aside from fresh installations where opencart.sql file can then handle.

**Comment by condor2** [comment]
Is not necessary.
On upgrade all extra tables from opencart.sql will be created

**Comment by TheCartpenter** [comment]
Ok. We still need a branch for opencart.sql file though.

**Comment by condor2** [comment]
What branch?

https://github.com/opencart/opencart-3/pull/39/files#diff-880ba7a3ba2dd91438579ab05abbefd08aa82145b614017a47bef72f15db1d82

**Comment by TheCartpenter** [comment]
My bad. I thought the affiliate reports used its own database table but it refers to the customers and pulls the data remotely in the report form. Let's give it a try.

**Pull request merged**
