### PR TITLE
Catalog Startup session code updated

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by condor2** [comment]
like in session :)

https://github.com/opencart/opencart-3/blob/main/upload/catalog/controller/startup/session.php

https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/currency.php

**Comment by TheCartpenter** [comment]
These two files do not mention a 1000. This is improvised. However, I do seem to have more $option array integration to do. I'll work on this.

**Comment by condor2** [comment]
No, because marketing now read expire from settings

https://github.com/opencart/opencart/blob/master/upload/catalog/controller/startup/marketing.php#L39

**Comment by TheCartpenter** [comment]
Yes, I am aware. Which is why I mentioned that I have to do more integration on this because of that and the reason why I can't take this pull request right now.

**Pull request closed without merging**
