### PR TITLE
Bootstrap updated to 3.4.1

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
```Bootstrap v3.3.7 (http://getbootstrap.com)```

**Comment by condor2** [comment]
If you click on File changed you will see Bootstrap 3.4.1

**Comment by condor2** [comment]
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

**Comment by TheCartpenter** [comment]
Now, the question I have for you; if I do ask for review about it, 'will you' leave this commit opened?

**Comment by condor2** [comment]
If you want to test a version with Bootstrap, Jquery, Summernote

https://github.com/condor2/opencart-3.0.x.x_Maintenance

**Comment by TheCartpenter** [comment]
Closing due to conflicts.

**Comment by TheCartpenter** [comment]
@condor2: I guess, now, would be a good time to test Bootstrap 3.7x with the upgraded jQuery.

**Pull request closed without merging**
