### PR TITLE
Fixed Affiliate custom fields not updated from Affiliate account

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
I think I found the issue regarding the OC forum troubleshooting. Your commit's still incomplete, however. Please grab a look at the catalog/view/theme/default/template/account/affiliate.twig file. You'll notice that the change you are acquiring for the array key name regarding 'affiliate' does not exist in that TWIG file. The affiliate_custom_field array name pulling the custom_field.custom_field_id 'does' exist but, as you'll notice, the custom_field array is used afterwards but no affiliate array key is showing there as you describe.

This is an old issue I used to have reported to Daniel before on the maintenance branch a while ago. Perhaps only a partial integration of the fix was merged or perhaps some spot were missing during the last investigation ...

The catalog/view/theme/default/template/account folder will need to be entirely reviewed before merging your suggestion as not only the affiliate key not only needs to be identified but also for the 'account' key name for customers, aside from affiliates, also needs to be identified.

If you could work on these arrays, I can leave this pull request opened for a bit a time but I would ask you to, please, prevent conflicts with your branches prior for me to merge your suggestions. If you'd also prefer, you could post these commits separately to avoid confusions with your modifications.

**Comment by TheCartpenter** [comment]
Furthermore, please test with print_r and provide with your next solution on this one. We need to ensure that the array results for the custom fields outputs accordingly from the browser prior to add the data into the database.

**Comment by TheCartpenter** [comment]
The template/affiliate and template/checkout also requires further patching since the affiliate and account array keys are also unidentified.

**Comment by condor2** [comment]
> The affiliate_custom_field array name pulling the custom_field.custom_field_id 'does' exist

You mean this?
https://github.com/opencart/opencart-3/blob/main/upload/catalog/controller/account/affiliate.php#L275-L283

**Comment by TheCartpenter** [comment]
Yes, these are included. Multiple catalog controllers needs these fixed.

**Comment by condor2** [comment]
And that command insert in database new values when an affiliate edit his affiliate information and change value from custom field

**Comment by TheCartpenter** [comment]
That is because, presently, no affiliate key are identified within their arrays nor are the account key when customers (without affiliation) applies while the OC forum users as well as your branch suggestions fix on the above implies the use of the affiliate key.

**Comment by TheCartpenter** [comment]
The other way around would be to remove all the entity keys and leave them with the indexes but, by doing that, Event Triggers won't provide full guarantee that the right custom fields would be pulled without identifying the array keys from the &$args.

**Comment by TheCartpenter** [comment]
The custom_field arrays from the master branch may help.

**Comment by TheCartpenter** [comment]
Fixed: https://github.com/opencart/opencart-3/commit/7a8bc369f22e2b472956e87a73b408b6bd911dc5 .

**Pull request closed without merging**
