### PR TITLE
Fixed javascript warnings

### PR DESCRIPTION
**Pull request by condor2**
https://github.com/opencart/opencart/blob/master/upload/system/library/document.php#L131

### CODE REVIEW

**Comment by mhcwebdesign** [comment]
Why not use this in the common/header.twig:

```
....
{% for script in scripts %}
<script src="{{ script }}" type="text/javascript"></script>
{% endfor %}
....

```
?

Don't make unnecessary cosmetic changes which break backward-compatibility with OC 3.0.3.8 and 3rd party extensions!

**Comment by TheCartpenter** [comment]
Because developers are encouraged to use the Event Engine starting from OC 4 and a great mount of users on the OC forum sticks to their objective to build a new future with their stores rather than sticking to the past with a workaround backward compatibility version.

**Comment by mhcwebdesign** [comment]
Err no, I posted it for the opencart-3 repository.

And your particular change to the common/header.twig was unnecessary as explained above.
And this particular issue exists regardless of whether using an event handler, OCmod, VQmod, or any other means of modifying core files in opencart-3. 

IMHO use 3.0.x.x_Maintenance and then jump straight to OpenCart 4 when it becomes more stable.

**Comment by mhcwebdesign** [comment]
My suggestion was for opencart-3. If you really want to attract users to opencart-3 you have to avoid unnecessary changes causing issues with backward compatibilities, there is no need for cosmetic changes.

**Pull request merged**
