### PR TITLE
Typo customer_form

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Not sure what you're suggesting here but even the maintenance has this line. By removing it the way you suggest it, it will create an expression missing error. However, the two closing brackets in one line from the next block of JS code should be removed. I'll take care of it.

**Comment by condor2** [comment]
Yes. Instead of deleting from line 928. I have deleted from line 713....

**Comment by TheCartpenter** [comment]
Just checked line 713, there's also nothing wrong with it. Each highlighter does point to the opening of the customer_group_id input accordingly.

**Comment by condor2** [comment]
I already told you....

**Comment by TheCartpenter** [comment]
No worries. At least, you were also notified.

**Pull request closed without merging**
