### PR TITLE
Added language variable for custom_field status

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
What you are suggesting is an increase of HTML table results by replacing the filter status with a column status and sort status instead of reducing the results by using the filters the way it's originally delivered from the core. Furthermore, the ```text_enabled``` and ```text_disabled``` are normally used for dropdown menus or checkbox purposes, as this suggestion proposes to use it within HTML rows while the ```text_yes``` and ```text_no``` already takes care of that from the core by the core language file without the need to add additional variables.

The use of ```$result['status']````, in this scenario, is used correctly since a ```filter_status``` returns a value of 1 or 0 depending on the selection chose by store owners with ```text_enabled``` and ```text_disabled```.  As for the ````$this->language->get('text_x') from the above fields in the array, extension developers can also use their own variables with a /before event while they might be dependable on adding their own ```text_enabled``` and ```text_disabled```.

Lastly, the unused query of the custom codes, you'd have to be a bit more specific about that as you seem to have also closed an identical proposal from the master branch's pull requests,

Therefore, this commit must be declined.

**Comment by condor2** [comment]
There is no Filter (like in Product List) so that code is unused....

**Comment by TheCartpenter** [comment]
Also take note on this model from the master branch: https://github.com/opencart/opencart/blob/master/upload/admin/model/customer/custom_field.php . The ```filter_status``` is not unused, it is indeed there. The reason why being that the code on the opencart-3 is being considered unused, as I can understand how not obvious it can be at times, is because that code needs to be completed by design.

**Comment by condor2** [comment]
And where that filters are used?

https://github.com/opencart/opencart/blob/master/upload/admin/view/template/customer/custom_field.twig
https://github.com/opencart/opencart/blob/master/upload/admin/view/template/customer/custom_field_list.twig

**Comment by TheCartpenter** [comment]
Since there are addressed concerns about leftover codes by design, then it would be to know why you decided to close your Pull Request commit from the master branch? ...

**Comment by condor2** [comment]
Maybe will add Filter in custom_field list for store owners who use 10.000 custom fields.

**Comment by TheCartpenter** [comment]
I would think the same thing here but that still wouldn't reflect the basis by design from OC 4 where those filters have also been removed before this day.

**Pull request closed without merging**
