### PR TITLE
JQuery updated to 3.6.0

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by condor2** [comment]
I don't think has time to review all changes on 3.x branch....

**Comment by TheCartpenter** [comment]
Yeah, I know. However, some requests may need reviewal process prior to make the change.

**Comment by condor2** [comment]
And 3.0.3.9 will be released in 2.0.2.4 =)))

**Comment by TheCartpenter** [comment]
That's why the more relevant bugfixes that needs to be pulled in the main branch, the faster we can solve these issues. I am still working on maintenance commits that were reported in the first place since there are leftover codes where the main branch still needs patching like SQL tables, fields, extension payments and shipping prefixes.

**Comment by condor2** [comment]
So update of jquery, summernote, bootstrap is not relevant :)

**Comment by TheCartpenter** [comment]
Nowhere to be said that this commit is irrelevant which is why, rather, it has been put under review for confirmation.

**Comment by Qvae** [comment]
This is my first time here so I don't fully get the rules and etiquette. Is this "verified" to work and is just waiting on Daniel to be accepted and "certified" to cause no issues to OC? So 
1/ If I were to do the steps in "files changed" it would basically...hopefully...work with no issue and I wouldn't get that vulnerability notification in google lighthouse? 
2/ Do I have to manually do these changes line for line, or is there some download that I'm not seeing or link to my site I can do to automatically do the changes?

**Comment by TheCartpenter** [comment]
@Qvae: For aspect 2, I would suggest to look on Google.

**Pull request closed without merging**
