### PR TITLE
jQuery updated to v3.6.0

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Requires minimum Bootstrap 3.4.1 release. Currently at: 3.3.5 .

**Comment by condor2** [comment]
With Bootstrap 3.4.1 you need to use sanitize: false for .popover to work or the entire code to be changed

**Comment by TheCartpenter** [comment]
Perhaps this solution for .popover: https://stackoverflow.com/a/67975329 .

**Comment by TheCartpenter** [comment]
If that can be applied from that link's suggestion, without the need to add that sanitize false, we could probably move forward with this.

**Comment by TheCartpenter** [comment]
Found another way. There's no need to focus on a JS integration if event triggers can be used by extension developers like the master branch in order to handle this. A simple /after event could resolve this from extensions.

**Pull request closed without merging**
