### PR TITLE
Removed duplicated code utf8 helper

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
I think this was discussed before on the 3.0.x.x branch. It throws errors in the phpstan but not sure if these are really meant to be duplicates or if they really need to go there, since it is still on the 3.0.x.x branch as well as we speak.

**Comment by condor2** [comment]
Why to keep same code twice in same function?...

https://github.com/opencart/opencart-3/blob/main/upload/system/helper/utf8.php#L119

https://github.com/opencart/opencart-3/blob/main/upload/system/helper/utf8.php#L187

https://github.com/opencart/opencart-3/blob/main/upload/system/helper/utf8.php#L247

**Comment by TheCartpenter** [comment]
Yes, I am aware. Which is why my previous reply also state that the 3.0.x.x branch still has these duplicated entries in the array.

**Comment by condor2** [comment]
Yes. Are duplicated in 3.0.x.x because never removed :)

**Comment by TheCartpenter** [comment]
Or, it may also be because the request has been declined from a previous PR on their branch.

**Comment by TheCartpenter** [comment]
Those duplicated keys and values looks like they are reset keys based on the previous indexes being used in the array; depending on the hex code. I'll close this, for now.

**Comment by condor2** [comment]
https://github.com/opencart/opencart/pull/13384

**Pull request merged**
