### PR TITLE
Same tracking code length when register as afilliate

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by condor2** [comment]
When you register an affiliate from admin, tracking code has 10 characters but when a client register as affiliate tracking code is 64...and is ugly to see in admin 10 and 64 characters for tracking code

**Comment by TheCartpenter** [comment]
I'm gonna give you a tip here. I just got one of my commit closed trying to explain a situation about the string types and, even there, he couldn't get it. Therefore, I would ask that you provide more explanation to why you'd want to change token(64) to token(10). I looked for other similarities where the models would use this but I don't see any.

**Comment by TheCartpenter** [comment]
Didn't see the notes on the above you added since you created this commit. I'll put a request on this one to see if it can be considered or not.

**Comment by condor2** [comment]
Why to have 2 length of tracking code when you can use one....

10 characters when you add an affiliate from admin side
https://github.com/opencart/opencart-3/blob/main/upload/admin/controller/customer/customer.php#L897

And 64 characters when a customer register as affiliate
https://github.com/opencart/opencart-3/blob/main/upload/catalog/model/account/customer.php#L130

Should be same length for both side....admin and catalog (10 with 10 or 64 with 64) ...

**Comment by TheCartpenter** [comment]
admin/controller/customer/customer.php - line 1175 has: ```$token = token(64);``` when logging in to customer's account.

**Comment by condor2** [comment]
Then change line 897 to token(64).....

**Comment by condor2** [comment]
Maybe now you understand...

Go to Admin, Customer add a new customer then go to Affiliate tab....
Tracking code has 10 characters.......

Then go to website and register directly as Affiliate....
tracking code now has 64 charachers.....

**Comment by TheCartpenter** [comment]
token(10) seem to have a winning range of 12 results in 11 files whereas the token(64) only has two results. Therefore, the token(10) from line 897 would be the right call. Perhaps the catalog/model/account/customer.php file is the one that needs to be changed to token(10). Submit an updated code change on this file in this repository and I'll see again if I can merge it. However, you'd need to re-open your commit.

**Pull request closed without merging**
