### PR TITLE
Fixed MySQLi PHP 8.1 warning

### PR DESCRIPTION
**Pull request by condor2**
https://github.com/opencart/opencart/pull/10437/files

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Doesn't show like this on the master branch but it does show similar with the maintenance branch. A bit harden to determine if this fix is about a user defined solution. Do you know a commit where this issue has been addressed previously?

**Comment by TheCartpenter** [comment]
I'll add it for now.

**Comment by condor2** [comment]
There is no commit.
But if this version will be compatible with PHP > 7.4 will be displayed a warning 

Unknown: mysqli::real_escape_string(): Passing null to parameter #1 ($string) of type string is deprecated in system\library\db\mysqli.php on line 53

No warning with old mysqli structure

**Comment by TheCartpenter** [comment]
It has been added now.

**Pull request merged**
