### PR TITLE
Update voucher_theme_list.twig

### PR DESCRIPTION
**Pull request by condor2**
Show "space" between buttons

### CODE REVIEW

**Comment by TheCartpenter** [comment]
You're still doing the same thing with that closing ```</div>```: https://github.com/opencart/opencart-3/pull/251 .

**Comment by condor2** [comment]
Without modification
v1

With modification
v2

**Comment by TheCartpenter** [comment]
The DIV must remain on the right. I will push the anchor and button on separated lines.

**Comment by TheCartpenter** [comment]
Done: https://github.com/opencart/opencart-3/commit/c617d58669fdc8b424335929ae7374cd6a7015f4 .

**Pull request closed without merging**
