### PR TITLE
sql updates

### PR DESCRIPTION
**Pull request by haxcop**
adding better logic for the date / datetime / date values, changes from MyISAM to InnoDB

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Other than the oc_country and the InnoDB Table Engine modifications, the rest is not needed.

**Comment by haxcop** [comment]
Hi, thanks for your prompt reply.
 I believe the dates are needed for two reasons:

1. `0000-00-00 date` formats are not longer accepted by default on mysql 8 and it's better and logically acceptable that when you are creating something to add the current date and also an expire date, this will perform better when doing queries 
2. applying the same logic to the structure, as you know will allow the users to have by default date,datetime already populated when adding or modify - it could also allow the user to modify such if needed.

let me know why is not needed, I'm curious about your reasons. 
thanks.

**Comment by danielkerr** [comment]
U are just posting rubbish. Just because something can be done. There's no advantage to ur commit but many disadvantages. 

Also all the dates are manually added because that's the way I want it.

**Comment by TheCartpenter** [comment]
> Hi, thanks for your prompt reply. I believe the dates are needed for two reasons:
> 
> 1. `0000-00-00 date` formats are not longer accepted by default on mysql 8 and it's better and logically acceptable that when you are creating something to add the current date and also an expire date, this will perform better when doing queries
> 2. applying the same logic to the structure, as you know will allow the users to have by default date,datetime already populated when adding or modify - it could also allow the user to modify such if needed.
> 
> let me know why is not needed, I'm curious about your reasons. thanks.

Sure, I'll give you one. Right now, what you're implying is only by your own words where you claim to encounter error messages when using 0000-00-00 but what I am not seeing is the actual error message you encountered probably due to the fact you're using strict mode.

Also, if what you're saying is true in regards to the optimization of those dates, then please provide the official documentation from dev.mysql.com for mySQL server library 8.x that describes your theory.

**Comment by haxcop** [comment]
Hi Thank you for answer, 
 in regards of date format:
 Besides an old ticket here: https://github.com/opencart/opencart/issues/9075
 This means MySQL by default works on Strict mode and not with customised defaults as you might have as well as I do, so this will always throw an error or Warning when using such incorrect dates 
if you Search for this error online you will get tons of references and why this date format shouldn't be used 
one of the main references from MySQL 
> Regular MySQL conf
>> mysql> SHOW VARIABLES LIKE 'sql_mode';
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.02 sec)
## The User Must set on MySQL conf
`SET SQL_MODE='ALLOW_INVALID_DATES';` https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_allow_invalid_dates
The Reason is: if you try to import a current opencart DB from one place (old) to a newly created one will always give you errors unless such modifications will be placed before, So, why to make things complicated when it can be easy and well done once? I belive this will improve the reputation of this great platform...

> Modify the current Globals 
>Notice the NO_ZERO_IN_DATE,NO_ZERO_DATE in the results above.
>>mysql> SET sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
Query OK, 0 rows affected, 1 warning (0.00 sec)`
>> https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date
Such dates of 0000-00-00 are OK only for development and doing things manually but not for Live Scenarios - which BTW hasn't change since the begining - "correct me if i am wrong please" @danielkerr 
### REF https://dev.mysql.com/doc/refman/8.0/en/date-and-time-types.html
>MySQL permits you to store a “zero” value of '0000-00-00' as a “dummy date.” In some cases, this is more convenient than using NULL values, and uses less data and index space. To disallow '0000-00-00', enable the [NO_ZERO_DATE](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date) mode.

## Performance
>Is it true when it comes to performance, the less validation the best performance you will get but also the less accurate and true result you will receive 

### That said
>If you have your catalog populated corectly with the right dates,column types and so on you will get an accurate result in less time as the value will be basically unique each time. 

Additionally
(I will do another request with an alteration for EAN,UPC,SKU,etc) as well as the Dates, those values should be treated as unique and not allow duplicates, Plus, Preconfigured Indexes (out of the box)

**Comment by ADDCreative** [comment]
@haxcop zero dates are actually used as a value in some of the code. Things like the discount, specials and coupons use a zero date to mean it's not date restricted. If you wanted to remove the use of zero dates you would also need to make other changes to parts of the code.

**Comment by haxcop** [comment]
@ADDCreative Hi 👋 ,
That's True, but the changes are mainly into the DB structure and won't affect the current code 
# The logic is:
## Scenario 1
* User create a Product, Discount, coupon, special price, etc... 
> The Discount still have the date fields available to choose the dates to and From but also there's a hidden field which is the created date `date_added` Which it should be automatically assigned and currently is not... this occurs on all the instances where's a `date_added` present
>>  Now we have a `date_start` which it COULD be defined by the user OR it could be automatically generated by the Database (This is a good practice )
>>> we do have `date_end` once again this Could and Basically should receive the User Input for security and even Marketing reasons, a good practice logic (but not mandatory),  should be to add a validation to not continue if there's no user input on this field and if there's no validation (no extra code line here) to have the DB assign a Maximum of One Year (My personal opinion, nothing last longer - see how the markets devaluate every year)... 
>>>> Finally `date_modified` This field is also hidden from the frontend and should be automatically populated by the DB, this could help to mantain any of the previus, in this way we know when was the last time the modification of such was made 

This is a good data structure in my opinion and there's also presence currently into the `oc_setting` Table `(0, 'config', 'config_invoice_prefix', CONCAT('INV-', YEAR(CURDATE()), '-00'), 0),`
But no other Table had it.

Such changes in the structure Won't affect the current code as it is, it will just add a correct date or date and time as required by each field IF there's no user input (as far as my test has show me...), If you belive some areas will throw an error but the correction will justify the code change, so why not? 
We will have a better Project as always

**Comment by ADDCreative** [comment]
@haxcop Sorry, I totally disagree with you on the `date_start` and `date_end`. These are usually used for customer group and quantity pricing, which you would not want to expire. The special pricing is for limited time special offers. If you had a site with thousands of products with dozens of customer groups, you wouldn't want forced dates in which you had to change all of the prices by.

Also setting the the default to CURRENT_DATE is not possible in MySQL 5.7 and equivalent versions of MariaDB.

**Comment by haxcop** [comment]
HI @ADDCreative 
Thanks fo your prompt reply, 
I've just checked in regards of MySQL 5.7 and MariaDB and these functions are totally compatible, as a matter of fact is in the opencart.sql since 
## MySQL
* Ref https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_current-date
## MariaDB
* Ref https://mariadb.com/kb/en/current_date/
> CURRENT_DATE is a Synonyms for CURDATE() 

I would like to explain this one more time,  and yes, you are correct too but `date_start` & `date_end` should be mandatory. and if is by customer group and this are as you are mentioning **special pricing** have an expirity date, but in a Customer Group like a **B2B** you could also add a **2038** if you wish 

I totally get your point and it's currently working as it is with some simple but ** Mandatory modifications ** on any MySQL server of preference (mariaDB too) in order to work properly, because the date formats are incorrect and that's a Fact.

I have my live systems currently working correctly with the current proposed changes.
Tested with:

* MysQL 5.7 / 8.x 
* MariaDB
* Vitess

Once again, thanks @TheCartpenter  & @ADDCreative for taking your time and Discuss this proposed changes. 
I will keep these on my Fork for future references.

**Comment by ADDCreative** [comment]
@haxcop It's not the functions aren't compatible. It's that they can't be use as defaults. See https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html. Expressions were added in version 8. MariaDB (tested 10.3.35) allows you to set an expression. However, when you come to insert a empty date, instead of getting the current date, it inserted a zero date anyway.

I personally don't like the idea of using arbitrary values such as 2038. If the zero dates need replacing they should be replaced with  null and the queries changed to match,

**Pull request closed without merging**
