### PR TITLE
Fixed affiliate custom_field not show in customer account when you ed…

### PR DESCRIPTION
**Pull request by condor2**
…it from admin

### CODE REVIEW

**Comment by TheCartpenter** [comment]
I see the affiliate array key from the custom_field array has been removed in your codes. I'll take a look at it in a moment. As for the backward escaped quotes on the SQL fields, I am currently working on that for all of the admin and catalog queries as we speak.

**Comment by condor2** [comment]
The bug was reported on forum....I need to find the topic :))

**Comment by TheCartpenter** [comment]
Then, yes, please refer the topic.

**Comment by condor2** [comment]
https://forum.opencart.com/viewtopic.php?f=202&t=227704#p839394

**Comment by TheCartpenter** [comment]
I remember this. According to this last post: https://forum.opencart.com/viewtopic.php?f=202&t=227704&start=40#p839732 , the final solution is still inaccurate as to know how to solve this issue entirely. There are still missing pieces to the puzzle. The rest of the pieces needs to be found in order to add these bugfixes since some says it works and others says it doesn't. It's a bit of a mixed situation on that topic.

**Comment by condor2** [comment]
Yes, affiliate part and customer part are a mess :))

**Comment by TheCartpenter** [comment]
Will close this for now until a definite solution has been found by supporters.

**Pull request closed without merging**
