### PR TITLE
Apply style

### PR DESCRIPTION
**Pull request by AJenbo**
- Update cs-fixer
- Align style in recently changed files
- Take advantage of more PHP 8.3 features

### CODE REVIEW

**Comment by TheCartpenter** [comment]
As much as I would like to merge these changes, @danielkerr did mentioned that it was not in his best interest to use the ```::class``` as there are no direct proof with PHP 8.3 that ```get_class``` should be replaced with ```:class``` and the OC Engine is based on object-oriented rather than static functions. Otherwise, it would be too mixed up as harder to follow the concept of the development of the project between releases. If you could please revert those back to ```get_class($e)```, I could merge the rest afterwards.

As for ```PayPal Checkout```, it may need to be restyled soon since I forgot to ```force-pushed``` the last change over existing files.

An aside feature to have: ```Symfony deprecation-contracts``` vendor with all dependencies being put up-to-date as per OC 4, if possible. On this branch, the vendors package have been updated with the exception of this vendor.

**Comment by TheCartpenter** [comment]
If an update for Symfony deprecation contracts can be done, also to consider the modifications to the ```library/twig/twig``` file.

**Comment by TheCartpenter** [comment]
I'll merge the changes and replace back the ```get_class($e)``` since there are only two files.

**Comment by AJenbo** [comment]
> there are no direct proof with PHP 8.3 that get_class should be replaced with :class 

https://wiki.php.net/rfc/class_name_literal_on_object

> the OC Engine is based on object-oriented rather than static functions.

This is not static vs OOP, it's dynamic constants vs procedural function calls

> If an update for Symfony deprecation contracts can be done, also to consider the modifications to the library/twig/twig file.

I'm unsure what you are referring to here, it doesn't appear to be related to this PR

**Pull request merged**
