### PR TITLE
Summernote updated

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
How confident on the level are we this summernote update will actually work with an older jQuery library version at this time?

**Comment by TheCartpenter** [comment]
The master branch uses the CKEditor rather than the summernote library and also involves a new parameter to pull the right language:

https://github.com/opencart/opencart/blob/master/upload/admin/view/template/catalog/category_form.twig#L219-#L222

**Comment by condor2** [comment]
> older jQuery library 

Yep..is old because you don't merge and Daniel same when update library......

**Comment by TheCartpenter** [comment]
To be fair, my previous question to you was asking 'how confident on the level are we this summernote will actually work' 'before' considering to merge it. So to add, you sent this pull request 'today' and you're the one who decided to close it - yourself.

**Pull request closed without merging**
