### PR TITLE
Added Compatibility  info when view an extension in Marketplace

### PR DESCRIPTION
**Pull request by condor2**

### CODE REVIEW

**Comment by TheCartpenter** [comment]
Language definition is missing.

**Comment by condor2** [comment]
Language definition is there
https://github.com/opencart/opencart-3/blob/main/upload/admin/language/en-gb/marketplace/marketplace.php#L29

**Comment by condor2** [comment]
You can see Compatibility info when browse on marketplace from a browser...but not from Opencart admin.

Now is more OK
marketplace

**Comment by TheCartpenter** [comment]
What you're presenting is a feature request, not a bugfix solutions. People are waiting for long time solutions about passed reported bugs. The compatibility might be added later on but is not our main priority right now, since people are waiting.

**Comment by condor2** [comment]
So is very hard to click on Merge this....
Ok, I will stop making pull requests.

**Comment by TheCartpenter** [comment]
You can still create pull requests. As said, it's not that this subject is closed but we need to focus on bugfixes at this time.

**Comment by IP-CAM** [comment]
> I will stop making pull requests. I will stop making pull requests.
would be a bad decision, considering the broad knowledge you have on v.3.x

**Pull request closed without merging**
